#---------------------------------------#
#            HELM REPOSITORY            #
#---------------------------------------#
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sealedsecrets-repo
  namespace: kube-utils
spec:
  interval: 1m
  url: https://bitnami-labs.github.io/sealed-secrets

#----------------------------------------#
#              HELM RELEASE              #
#----------------------------------------#
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealedsecrets-operator
  namespace: kube-utils
spec:
  interval: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: '>=1.15.0-0'
      sourceRef:
        kind: HelmRepository
        name: sealedsecrets-repo
  targetNamespace: kube-utils
  install:
    createNamespace: false
  values:
    fullnameOverride: sealed-secrets-controller
