#---------------------------------------#
#            HELM REPOSITORY            #
#---------------------------------------#
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mongodb-repo
  namespace: microchess
spec:
  interval: 12h
  url: oci://registry-1.docker.io/bitnamicharts
  type: oci

#----------------------------------------#
#              HELM RELEASE              #
#----------------------------------------#
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: microchess
spec:
  interval: 1h
  chart:
    spec:
      chart: mongodb
      version: ">=18.0.0 <19.0.0"
      sourceRef:
        kind: HelmRepository
        name: mongodb-repo
        namespace: microchess
  values:
    architecture: replicaset
    replicaCount: 1
    auth:
      enabled: false
    persistence:
      enabled: true
      storageClass: longhorn
      size: 5Gi
      accessModes:
        - ReadWriteOnce
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    livenessProbe:
      enabled: true
    readinessProbe:
      enabled: true
    metrics:
      enabled: false