#---------------------------------------#
#            HELM REPOSITORY            #
#---------------------------------------#
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rabbitmq-repo
  namespace: microchess
spec:
  interval: 12h
  url: oci://registry-1.docker.io/bitnamicharts
  type: oci

#----------------------------------------#
#              HELM RELEASE              #
#----------------------------------------#
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: microchess
spec:
  interval: 1h
  chart:
    spec:
      chart: rabbitmq
      version: ">=16.0.0 <17.0.0"
      sourceRef:
        kind: HelmRepository
        name: rabbitmq-repo
        namespace: microchess
  values:
    global:
      security:
        allowInsecureImages: true
    image:
      registry: docker.io
      repository: "bitnamilegacy/rabbitmq"
      tag: "4.1.3-debian-12-r1"
    replicaCount: 1
    auth:
      username: microchess
      password: microchess
      erlangCookie: microchess
    persistence:
      enabled: true
      storageClass: longhorn
      size: 5Gi
      accessModes:
        - ReadWriteOnce
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    livenessProbe:
      enabled: true
    readinessProbe:
      enabled: true
    metrics:
      enabled: false